version: '3.8'
services:
  jenkins:
    image: jenkins/jenkins:lts
    privileged: true
    user: root
    ports:
      - 8080:8080
      - 50000:50000
    container_name: jenkins-django
    volumes:
      - /srv/data/jenkins_data:/jenkins_home
      - /srv/data/jenkins:/var/jenkins_config
      # - /home/${myname}/jenkins_compose/jenkins_configuration:/var/jenkins_home
      # - /var/run/docker.sock:/var/run/docker.sock
volumes:
  jenkins_data:
    driver: local
  jenkins:
    driver: local
